### ISSUE TITLE
Unable to connect to a project

### ISSUE THREAD

**Issue by dusky3** [rundis/elm-light#13]
Hi,
when I try to add connection to an elm project I get the following error:

```
We couldn't connect.

Looks like there was an issue trying to connect to the project. Here's what we got:
/home/dusky/.config/LightTable/plugins/elm_light/node/elm-client.js:161
function send(msg) { process.send(msg); }
                             ^

TypeError: process.send is not a function
    at send (/home/dusky/.config/LightTable/plugins/elm_light/node/elm-client.js:161:30)
    at startMessageListener (/home/dusky/.config/LightTable/plugins/elm_light/node/elm-client.js:349:3)
    at /home/dusky/.config/LightTable/plugins/elm_light/node/elm-client.js:409:9
    at Socket.<anonymous> (/home/dusky/.config/LightTable/plugins/elm_light/node/elm-client.js:50:7)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at Pipe.onread (net.js:523:20)
```

Any suggestions? Your help is greatly appreciated.

**Comment by rundis** [comment]
Weird. 
What version of Light Table and what version of elm-light ?

**Comment by dusky3** [comment]
I got error with LightTable 0.8 and elm-light 0.1.3 so I updated yesterday to 0.8.1 and 0.3.3 and I get the same error.

I have 64bit Void linux and had built LightTable from source.

**Comment by rundis** [comment]
I'm a bit at loss here. I've tried this on os/x, windows (10) and ubuntu (14.04). I've tried a clean rebuild and still it works. In LT I do a process.fork and according to the node doc for child_process this should be what's needed for process.send to be available for a child process. I'm not sure what more I can do to resolve your problem bar setting up a container with void linux and follow the exact steps you have taken.
- Clutching at straws here, but what version of node did you use when building Light Table ? I wouldn't think this should matter, but just maybe it does.
- Could you try a clean pre-buildt Light Table 0.8.1 (ie download tar from LightTable.com) if you haven't already

**Comment by dusky3** [comment]
Thank you @rundis for your time, advice and the great plugin. I've downloaded the pre-built binary and everything seems to work now.

PS & FYI: I have node version 5.0.0 and npm version 3.5.0
