### ISSUE TITLE
Feature request: types

### ISSUE THREAD

**Issue by ccapndave** [rundis/elm-light#14]
It would be incredibly useful if you could highlight something in the editor and run a command that pops up what type the Elm compiler has inferred for it.  Is this even conceptually possible?

**Comment by rundis** [comment]
I believe it's possible, but it's far from trivial to do at the moment. It would be really nice if the elm-compiler (or through some elm-tooling api) this was exposed to external tools. I think implementing type inference in the elm-light plugin (or vs code for that matter) would be a lot of effort which would be better suited as something more general.

**Comment by rundis** [comment]
Needs xompiler feature. Tracked as feature request in elm-compiler. Will reopen when/if some sort of support for tooling on this makes it into the compiler..
