### ISSUE TITLE
Linter: error details at the bottom of a file

### ISSUE THREAD

**Issue by sygour** [rundis/elm-light#16]
After linting a file with an error on one of the last lines (of the screen), if I run the command `Linter: Show details at cursor` the error description is cut like this for example:

```
Cannot find variable `updateR`
Maybe you want one of the following?
```

**Comment by rundis** [comment]
@sygour Tx for the report. I'll look into it and hopefully have a fix soon.

**Comment by sygour** [comment]
Thanks @rundis 
It's a minor bug though! The plugin works great otherwise, keep up the good work!
