### ISSUE TITLE
Docs for own project

### ISSUE THREAD

**Issue by mordrax** [rundis/elm-light#20]
Currently bringing up the docs only work for imported elm packages. It'll be awesome if it could also bring up our own modules. And also local functions in the same module.

**Comment by rundis** [comment]
I'd love to. But currently all docs are retrieved using [elm-oracle](https://github.com/ElmCast/elm-oracle). That in turn is using package docs to provide signatures+docs, but only for 3rd party packages.

Using generated docs as a way to retrieve information is obviously very very limited (docs are only generated (by elm-make) for packages. Whether your elm project is a package or not is inferred by the presence of modules in the `"exposed-modules"` key in `elm-package.json`. And only for exposed/public definitions/functions.

So basically one would need to do parsing. Parsing elm code is not trivial, but of course doable. But my understanding is that elm-oracle is undergoing a rewrite to do parsing and provide much more insight. However I have no idea about it's progress. I also know that there are plans to expose the AST from elm-format at some point in the future which also would be very helpful. 

I've sort of settled for waiting a while longer for elm-oracle and/or elm-format to help me do the tougher bits, but maybe at some point my patience will run out and I'll try to give it a shot.

**Comment by mordrax** [comment]
Thanks for the in-depth answer, helps me understand how this all fits together on a higher level.
