### ISSUE TITLE
autoclose-brackets doesn't work for quotes correctly

### ISSUE THREAD

**Issue by nukecoder** [rundis/elm-light#21]
using this: `[:editor :lt.objs.editor/autoclose-brackets]` for autoclosing `[{"(` works in clojure and clojurescipt files, but in an elm file it only works correctly for `[{(`

The issure seems to be with the linter?
- Type `"` -> Highlights it in red => `"`
- Type another `"` -> Highlight goes away, second `"` is added and auto-closed => `"""`
- Typing another `"` moves the cursor through the third `"` as it should

**Comment by rundis** [comment]
I almost forgot about that one. I discovered it but thought it was my set up. I'll look into it.
As a workaround you could try adding the following to your user keymap:

`[:editor.elm.common "\""  (:editor.open-pair "\"")]`

**Comment by nukecoder** [comment]
That gets ride of the highlight, but otherwise it works the same. Inserts only one `"` and on second keypress inserts a pair of `"`
