### ISSUE TITLE
Feature request:  Tooltips on hover

### ISSUE THREAD

**Issue by 7sharp9** [rundis/elm-light#22]
This feature exists in the vscode Elm plugin and I use it all the time, it would be really nice to have :-)

**Comment by rundis** [comment]
Does it have to be hover as in mouse hover ?
If not, just place the cursor over a function/type and press ctrl-d (/cmd-d). If Elm oracle finds docs for it  it's displayed inline. ctrl-d/cmd-d to remove the inline doc again.

(sample, with cursor placed in div)
![screen shot 2016-06-28 at 19 56 15](https://cloud.githubusercontent.com/assets/399197/16426620/25a17da4-3d6a-11e6-8287-6c282ec50f3c.png)

**Comment by 7sharp9** [comment]
I guess it doesn't have to be via mouse, Im just used to the behaviour in the vscode plugin :-)

Nice work by the way, Im torn between vscode and lightable now :-/

**Comment by rundis** [comment]
Im not going to change the current behaviour this time round. Basically std LT behaviour.
