### ISSUE TITLE
ReferenceError: dialogs is not defined

### ISSUE THREAD

**Issue by abhinavzspace** [rundis/elm-light#28]
I am getting the following error when I click on `Connect: Add Connection`.
I just installed LightTable version 0.8.1 on Mac OS.

`
ReferenceError: dialogs is not defined
    at eval (/Users/abhinav/Library/Application%20Support/LightTable/plugins/elm_light/elm-light_compiled.js:17047:346)
    at HTMLLIElement.<anonymous> (file:///Applications/LightTable.app/Contents/Resources/app/core/node_modules/lighttable/bootstrap.js:32898:108)
`

**Comment by rundis** [comment]
Tx for the report. I can confirm that the error is reproducible.

As a workaround just use the autoconnect feature. For example:
- open any .elm file in your project
- open command pane (ctrl+space)
- type "Elm lint" select the command "Elm: Lint selected file"
- It will then connect to the project automatically and once done lint the file to display and errors or warnings 

let me know if that helps !

**Comment by abhinavzspace** [comment]
It is working like this. Thanks!

**Comment by rundis** [comment]
Will be included in the next patch release.
