### ISSUE TITLE
AST Error on valid file

### ISSUE THREAD

**Issue by superguru** [rundis/elm-light#30]
Example code:

```
import Html exposing (text)
main =
  text "Hello, World!"
```

Starting elm-light 0.4.2 connection in Light Table 0.8.1 with elm 0.17.1 gives this in the console:

> {:message "Expected \"effect\", \"module\" or \"port\" but \"i\" found.", :expected [{:type "literal", :value "effect", :description "\"effect\""} {:type "literal", :value "module", :description "\"module\""} {:type "literal", :value "port", :description "\"port\""}], :found "i", :location {:start {:offset 0, :line 1, :column 1}, :end {:offset 1, :line 1, :column 2}}, :name "SyntaxError"}

The same file works perfectly in elm reactor.

**Comment by rundis** [comment]
Tx.

It's a known limitation. In Elm a module declaration is optional. I tend to always provide one, but Elm opted to make it optional to make it easy to get started.

Until a fix comes out, the workaround is to  just give your module a module declaration (at the top of your module)

`module MyModule exposing (..)`

**Comment by rundis** [comment]
Will be included in the next release.

**Comment by superguru** [comment]
Yup, this fixes it. Thanks.
