### ISSUE TITLE
"Testing" in documentation

### ISSUE THREAD

**Issue by Spenhouet** [rundis/elm-light#34]
In the documentation (https://rundis.gitbooks.io/elm-light-guide/content/features.html) the lable "Testing" is there twice:

![Testing](https://cloud.githubusercontent.com/assets/7819068/20369435/39069c22-ac59-11e6-8b00-ccdc07896544.JPG)

The first link does work, the second doesn't (it's not clickable).

I just thought i would point that out.

**Comment by rundis** [comment]
Tx!

**Comment by rundis** [comment]
Fixed in https://github.com/rundis/elm-light-guide/commit/edee450c5ec7ea6d587b825833fe376cae843339
