### ISSUE TITLE
No 'elm-light' plugin found

### ISSUE THREAD

**Issue by rudolf-adamkovic** [rundis/elm-light#38]
I installed Light Table on my Mac and followed the official instructions:

> Install the plugin from the Light Table Plugin Manager.
> 1. In Light Table open the commands tab (default ctrl+space or use the menu View->Commands)
> 2. In the commands tab search field enter something like "plugin manager" and select the item Plugins: > Show plugin manager
> 3. In the search field for plugins type elm and press enter
> 4. You should have an item named elm-light Click the install button to the right

I search for `elm` and get no results:

<img width="650" alt="screen shot 2017-01-20 at 14 50 53" src="https://cloud.githubusercontent.com/assets/1158274/22151780/e0bfc27e-df1f-11e6-86df-779c35137bc0.png">

**Comment by rundis** [comment]
Could you try one more time. Sometimes the plugin manager is a bit slow to updare it´s plugin list.

**Comment by rudolf-adamkovic** [comment]
@rundis 

> Could you try one more time.

Tried again. Nothing. 😞

**Comment by rundis** [comment]
1) Did you close the plugin manager window/tab ?
2) Could you check your console if you have any error messages (ctrl-space -> Toggle console)
3) Are you behind a proxy ?
4) First time you installed Light Table on that machine ?
5) Can you find other plugins (try searching for something like "lint") ?

A little context:
- Light Table downloads the list of available plugins from Github and then populates the list
- Once you have installed a plugin it will displayed in your "Installed" tab (and will not show up in the "Available tab"

Some people (especially people behind a company proxy) have had problems with github access, it has also been a few cases were people have been hit by githubs rate-limiting policy.


Sorry you are having trouble with this, I'm 99.9 % certain it's nothing to do with the plugin and all to do with Light Table, but that doesn't help you much though (:

**Comment by rudolf-adamkovic** [comment]
@rundis 

> Did you close the plugin manager window/tab ?

Yes. I tried to close, open, wait, ...

> Could you check your console if you have any error messages (ctrl-space -> Toggle console)

No messages:

<img width="704" alt="screen shot 2017-01-21 at 00 21 08" src="https://cloud.githubusercontent.com/assets/1158274/22168806/a6a857f4-df6f-11e6-9fda-a087af1b7a91.png">

> Are you behind a proxy ?

No.

> First time you installed Light Table on that machine ?

Yes.

> Can you find other plugins (try searching for something like "lint") ?

7 results, showing immediately:

<img width="647" alt="screen shot 2017-01-21 at 00 23 16" src="https://cloud.githubusercontent.com/assets/1158274/22168827/d75446c4-df6f-11e6-9b09-a6fda9025e61.png">

**Comment by rudolf-adamkovic** [comment]
@rundis 

Turns out, an older version of `elm-light` was installed already!

Lesson learned: Search **does not** work across Installed and Available like elsewhere. It searches just the Available list. 

So, all is good now:

<img width="253" alt="screen shot 2017-01-21 at 11 46 23" src="https://cloud.githubusercontent.com/assets/1158274/22173869/41d7d2b8-dfcf-11e6-9916-a16596ca3b3f.png">

Also, correction:

> First time you installed Light Table on that machine?

~~Yes.~~ No.

Thank you @rundis for your help! Closing.
