### ISSUE TITLE
can see red underline, but no error message

### ISSUE THREAD

**Issue by mbylstra** [rundis/elm-light#7]
![elm-light-error-not-showing](https://cloud.githubusercontent.com/assets/702885/11894357/af86abb2-a5ca-11e5-9f08-98bf96c35f3a.png)

Hi,

I am using elm-light 0.3.0 with lighttable-0.8.0-linux (Ubuntu 1404). I can see the red line as you can see in the screenshot, however I can't figure out how to show the error message. In the Readme file the error message show up as a red rectangle that covers the text below it. How do I make that appear? Mousing over the line or clicking on it does not seem to have an effect. There is also nothing showing in the console (in the screenshot, the console is open).

I noticed that when run the repl on a line (CTRL+ENTER), an error does show. You can see this here:
![elm-light-repl-error-showing](https://cloud.githubusercontent.com/assets/702885/11894778/95f3c830-a5cd-11e5-91d9-19dfe35679d3.png)

I was quite happy with the big red error messages in 0.1x, so if this looks like it might be a difficult problem to fix (maybe it's platform specific), I would be very happy if there was a configuration flag that enabled the "space filling" style of error messages as in 0.1.x and like the repl error above.

Thanks for making this awesome plugin!

**Comment by rundis** [comment]
Cheers !

https://github.com/rundis/elm-light#511-details-and-navigation
the command you are looking for is "Linter: Show details at cursor" 

The previous style of showing results had a limitation when you have more than one error on a line (which is quite possible!). The new style is a bit inspired by IntelliJ where you can "alt-enter" on any error/warning to show details (and at some point in the future, when elm-make provides even richer Info,  I might even be able to provide options/suggestions for fixes in the dialog)

I think a mouseover behaviour shouldn't be to hard to implement. Feel free to add a separate issue for that if you feel that would be useful.

**Comment by mbylstra** [comment]
I feel silly - I totally missed this section! Thanks for the help. I quite liked the big upfront errors in the old version, but I can see how it would be an issue with multiple errors on the line.
