### ISSUE TITLE
inline eval output caries some unnecessary characters

### ISSUE THREAD

**Issue by thisredone** [rundis/elm-light#9]
![image](https://cloud.githubusercontent.com/assets/1191844/12170311/911ce364-b540-11e5-9280-4bd08f1394c3.png)

Seems like a `|` for every line in the evaluated code which gets a little ridiculous at times ;-)

![image](https://cloud.githubusercontent.com/assets/1191844/12170343/cdb8bb86-b540-11e5-9e0e-0ee4de4ddd10.png)

**Comment by rundis** [comment]
yeah that sucks. I'll look into it tnite. Tx for the report.

**Comment by rundis** [comment]
fixed in 0.3.2
